CREATE TABLE session_treino
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    treino_id      BIGINT,
    exercicio_id   BIGINT,
    series         INT,
    repeticoes     INT,
    carga          DOUBLE PRECISION,
    tempo_descanso VARCHAR(255),
    CONSTRAINT pk_session_treino PRIMARY KEY (id)
);

ALTER TABLE session_treino
    ADD CONSTRAINT FK_SESSION_TREINO_ON_EXERCICIO FOREIGN KEY (exercicio_id) REFERENCES exercicios (id);

ALTER TABLE session_treino
    ADD CONSTRAINT FK_SESSION_TREINO_ON_TREINO FOREIGN KEY (treino_id) REFERENCES treinos (id);