CREATE TABLE usuarios
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    senha           VARCHAR(255)                            NOT NULL,
    nome            VARCHAR(255)                            NOT NULL,
    data_nascimento date,
    telefone        VARCHAR(255),
    genero          VARCHAR(255),
    altura          DOUBLE PRECISION,
    peso            DOUBLE PRECISION,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_email UNIQUE (email);