CREATE TABLE treinos
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(255)                            NOT NULL,
    objetivo     SMALLINT,
    data_criacao date,
    ativo        BOOLEAN                                 NOT NULL,
    usuario_id   BIGINT,
    CONSTRAINT pk_treinos PRIMARY KEY (id)
);

ALTER TABLE treinos
    ADD CONSTRAINT FK_TREINOS_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuarios (id);