CREATE TABLE exercicios
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome           VARCHAR(255)                            NOT NULL,
    descricao      CLOB,
    grupo_muscular VARCHAR(255),
    CONSTRAINT pk_exercicios PRIMARY KEY (id)
);